session_name: fabrics_background
shell_command_before:
- cd /home/mspahn/catkin_robothon
- source devel/setup.zsh
windows:
  - window_name: controller
    layout: tiled
    panes:
      - roscore
  - window_name: platonics_vision
    layout: tiled
    panes:
      - roslaunch platonics_vision depth_camera.launch rviz:=False --wait
      - rosrun platonics_vision sift_service
      - rosrun platonics_vision iterative_sift_service
      - rosrun platonics_vision slider_solver_action_server
  - window_name: lfd
    layout: tiled
    panes: 
      - rosrun skills_manager lfd_servers
      - roslaunch rosbridge_server rosbridge_websocket.launch --wait
  - window_name: utils
    layout: tiled
    panes: 
      - rosrun platonics_tools nodes_checker
      - roslaunch spacenav_node classic.launch --wait
      - cd src/platonics_gui; npm run start
      - rosrun skills_manager recording_node
